package ai.phast.ctdynamo;

import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;

import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * The publicly visible functions to build mocks usable with ctDynamo.
 *
 * <p>You could use something like Mockito, but that can be difficult because the tables etc. generated by ctDynamo are
 * complex. These mocks let you create your own database, with exactly the values you want, thus using the actual
 * table code during your unit tests. That is, it is the DynamoDb client that is mocked, not the table code.
 */
public class DynamoMockUtil {

    /**
     * Private constructor - this is a utility class, should not be instantiated
     */
    private DynamoMockUtil() {}

    /**
     * Build a mock table backed by an empty database. The table name will be "mock"
     * @param tableClass The class to mock
     * @param <T> The type of item stored in the table
     * @param <TableT> The DynamoTable class
     * @return A table backed by an empty database
     */
    public static <T, TableT extends DynamoTable<T, ?, ?>> TableT buildMockTable(Class<TableT> tableClass) {
        return buildMockTable(tableClass, "mock", (List<T>)null);
    }

    /**
     * Build a mock table backed by a database with initialItems in it
     * @param tableClass The class to mock
     * @param tableName The name of the table
     * @param initialItems The items to put into the database when it is created
     * @param <T> The type of item stored in the table
     * @param <TableT> The DynamoTable class
     * @return A table backed by an empty database
     */
    @SafeVarargs
    public static <T, TableT extends DynamoTable<T, ?, ?>> TableT buildMockTable(Class<TableT> tableClass, String tableName, T... initialItems) {
        return buildMockTable(tableClass, tableName, Arrays.asList(initialItems));
    }

    /**
     * Build a mock table backed by a database with initialItems in it. The table name will be "mock"
     * @param tableClass The class to mock
     * @param initialItems The items to put into the database when it is created
     * @param <T> The type of item stored in the table
     * @param <TableT> The DynamoTable class
     * @return A table backed by an empty database
     */
    @SafeVarargs
    public static <T, TableT extends DynamoTable<T, ?, ?>> TableT buildMockTable(Class<TableT> tableClass, T... initialItems) {
        return buildMockTable(tableClass, "mock", Arrays.asList(initialItems));
    }

    /**
     * Build a mock table backed by a database with initialItems in it. The table name will be "mock"
     * @param tableClass The class to mock
     * @param initialItems The items to put into the database when it is created
     * @param <T> The type of item stored in the table
     * @param <TableT> The DynamoTable class
     * @return A table backed by an empty database
     */
    public static <T, TableT extends DynamoTable<T, ?, ?>> TableT buildMockTable(Class<TableT> tableClass, Collection<T> initialItems) {
        return buildMockTable(tableClass, "mock", initialItems);
    }

    /**
     * Build a mock table backed by a database with initialItems in it
     * @param tableClass The class to mock
     * @param tableName The name of the table
     * @param initialItems The items to put into the database when it is created
     * @param <T> The type of item stored in the table
     * @param <TableT> The DynamoTable class
     * @return A table backed by an empty database
     * @throws IllegalArgumentException If the table doesn't have the constructor that all ctDynamo-generated tables have
     * @throws RuntimeException If there is an exception thrown while creating the table
     */
    public static <T, TableT extends DynamoTable<T, ?, ?>> TableT buildMockTable(Class<TableT> tableClass, String tableName, Collection<T> initialItems) {
        try {
            // We have a chicken and egg problem here. We need to examine the table to build our mock dynamo client, but we
            // can't get a table until after we build our mock dynamo client. The solution is to build a dummy dynamo client
            // that is just good enough to let us build a table, use that table to build the mock dynamo client, then build
            // a second table on top of the mock.
            var constructor = tableClass.getConstructor(DynamoDbClient.class, String.class);
            var dummyClient = new DynamoDbClient() {
                @Override
                public void close() {
                }

                @Override
                public String serviceName() {
                    return null;
                }
            };
            var tableInstance = constructor.newInstance(dummyClient, tableName);
            var items = (initialItems == null
                         ? null
                         : initialItems.stream().map(tableInstance::encode).collect(Collectors.toList()));
            return constructor.newInstance(new MockDynamoClient(tableInstance, items), tableName);
        } catch (NoSuchMethodException ex) {
            throw new IllegalArgumentException("Class " + tableClass.getSimpleName() + " must be a dynamo table class generated by ctdynamo");
        } catch (InstantiationException | IllegalAccessException | InvocationTargetException ex) {
            throw new RuntimeException("Error creating mock for class " + tableClass.getSimpleName(), ex);
        }
    }

    /**
     * Get all items from the table. This pulls them directly from the mock client backing store, it does not
     * go through getItem(), query(), or scan().
     * @param table The table to read the items from
     * @param <T> The type of the item
     * @return A list of all items in the table (order not guaranteed)
     */
    public static <T> List<T> getItems(DynamoTable<T, ?, ?> table) {
        synchronized (table) {
            return getMockClient(table).getStore().getItems().map(table::decode).collect(Collectors.toList());
        }
    }

    /**
     * Encode an item into a Dynamo attribute-value map. Useful for testing.
     * @param table The table that will store the item
     * @param item The item to encode
     * @param <T> The type of the item
     * @return The item encoded into an attribute value map
     */
    public static <T> Map<String, AttributeValue> encode(DynamoTable<T, ?, ?> table, T item) {
        return table.encode(item);
    }

    /**
     * Decode an item from an attribute value map
     * @param table The table that can store the item
     * @param item The attribute value map representing the item
     * @param <T> The type of the item
     * @return The item, after decoding
     */
    public static <T> T decode(DynamoTable<T, ?, ?> table, Map<String, AttributeValue> item) {
        return table.decode(item);
    }

    /**
     * Ensure all expected items are in the table
     * @param table The table to examine
     * @param expectedItems Items to expect
     * @throws AssertionError If any item is missing from the table
     * @param <T> The type of item in the table
     */
    @SafeVarargs
    public static <T> void verifyContains(DynamoTable<T, ?, ?> table, T... expectedItems) {
        verifyContains(table, Arrays.asList(expectedItems));
    }

    /**
     * Ensure all expected items are in the table
     * @param table The table to examine
     * @param expectedItems Items to expect
     * @throws AssertionError If any item is missing from the table
     * @param <T> The type of item in the table
     */
    public static <T> void verifyContains(DynamoTable<T, ?, ?> table, Collection<T> expectedItems) {
        Map<Map<String, AttributeValue>, T> keyToItem;
        var client = getMockClient(table);
        synchronized (table) {
            keyToItem = client.getStore().getItems()
                              .collect(Collectors.toMap(client::toKey, table::decode));
        }
        for (var item: expectedItems) {
            var actualItem = keyToItem.get(client.toKey(table.encode(item)));
            assert actualItem != null : "Item " + item + " not in table";
            assert actualItem.equals(item) : "Expected " + item + ", got " + actualItem;
        }
    }

    /**
     * Ensure that the table has the given items and no others
     * @param table The table to examine
     * @param expectedItems The items expected to be found in the table
     * @throws AssertionError If any item is missing from the table, or if the table has items not in expectedItems
     * @param <T> The type of item in the table
     */
    @SafeVarargs
    public static <T> void verifyContainsExactly(DynamoTable<T, ?, ?> table, T... expectedItems) {
        verifyContainsExactly(table, Arrays.asList(expectedItems));
    }

    /**
     * Ensure that the table has the given items and no others
     * @param table The table to examine
     * @param expectedItems The items expected to be found in the table
     * @throws AssertionError If any item is missing from the table, or if the table has items not in expectedItems
     * @param <T> The type of item in the table
     */
    public static <T> void verifyContainsExactly(DynamoTable<T, ?, ?> table, Collection<T> expectedItems) {
        synchronized(table) {
            var dbSize = getMockClient(table).getStore().size();
            assert expectedItems.size() == dbSize : "Expected " + expectedItems.size() + " items, found " + dbSize;
            verifyContains(table, expectedItems);
        }
    }

    /**
     * Git the mock client from a table
     * @param table The table
     * @return The mock client that the table is built on top of
     * @throws RuntimeException If the table has something other thon a MockClient backing it
     */
    private static MockDynamoClient getMockClient(DynamoTable<?, ?, ?> table) {
        try {
            return (MockDynamoClient)table.getClient();
        } catch (ClassCastException e) {
            throw new RuntimeException("The table passed in must be created with MockUtil.buildMockTable");
        }
    }
}
