package ai.phast.ctdynamo.processorTest;

import ai.phast.ctdynamo.annotations.DynamoItem;
import ai.phast.ctdynamo.annotations.DynamoPartitionKey;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.List;
import java.util.Map;

/**
 * Test of annotation processor. This includes autogenerated codecs.
 */
@DynamoItem
@Setter
@Getter
@ToString
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class OuterItem {

    public enum Flavor { SWEET, SALTY, SOUR, BITTER, UMAMI }

    @DynamoPartitionKey
    private String partition;

    private InnerItem inner;

    private List<InnerItem> listOfInner;

    private Map<String, Integer> mapOfInt;

    private Map<Flavor, String> flavorMap;
}
